name: Cloudflare Tunnel 2

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  CreateTunnel:
    runs-on: ubuntu-latest
    timeout-minutes: 320
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y curl wget

    - name: Download cloudflared installer
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb -O cloudflared.deb

    - name: Install cloudflared
      run: |
        sudo dpkg -i cloudflared.deb

    - name: Install Express
      run: |
        npm install express
      
    - name: Run App and Create Tunnel
      run: |
        cloudflared tunnel --url http://localhost:8080 > output.txt 2>&1 &
        sleep 10
        node setLink.js &
        npm run start
        
